config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  has_merit
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  acts_as_follower
  acts_as_followable

  has_many :posts
  has_many :comments
  has_many :events

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, AvatarUploader

  validates_presence_of :name

  self.per_page = 10

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :check_ownership, only: [:edit, :update]
  respond_to :html, :js

  def show
    @activities = PublicActivity::Activity.where(owner: @user).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def deactivate
  end

  def friends
    @friends = @user.following_users.paginate(page: params[:page])
  end

  def followers
    @followers = @user.user_followers.paginate(page: params[:page])
  end

  def mentionable
    render json: @user.following_users.as_json(only: [:id, :name]), root: false
  end

  private

  def user_params
    params.require(:user).permit(:name, :about, :avatar, :cover,
                                 :sex, :dob, :location, :phone_number)
  end

  def check_ownership
    redirect_to current_user, notice: 'Not Authorized' unless @user == current_user
  end

  def set_user
    @user = User.friendly.find_by(slug: params[:id]) || User.find_by(id: params[:id])
    render_404 and return unless @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def options_for_seasons
    [['Male', 'male'], ['Female', 'female']]
  end

  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - (dob.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def is_current_user?(user)
    user == current_user
  end
end

app/views/users/_user.html.erb
<br>
<div id="user-<%= user.id %>" class="row">
  <div class="col-lg-8">
    <%= render 'shared/avatar', user: user %>
    <h5 class="name"><%= link_to user.name, user %></h5>
  </div>
  <div class="col-lg-4">
    <div class="follow">
      <%= render 'follows/form', user: user %>
    </div>
  </div>
</div>
<br>

app/views/users/deactivate.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h3>Deactivate</h3>
      <hr>
      <h5>Unhappy with UnitedP? Hit the Button below to cancel account.</h5>
      <br>
      <%= button_to 'Cancel my account', registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h3>Edit Profile</h3>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :avatar %>
          <br>
          <%= render 'shared/avatar', user: @user %>
          <br>
          <br>
          <%= f.file_field :avatar %>
        </div>
        <div class="form-group">
          <%= f.label :cover %>
          <br>
          <%= render 'shared/cover', user: @user %>
          <br>
          <%= f.file_field :cover %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :about %>
          <%= f.text_area :about, placeholder: 'About', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, placeholder: 'Location', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :church %>
          <%= f.text_field :church, placeholder: 'church', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, placeholder: 'Phone Number', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :dob %>
          <%= f.text_field :dob, placeholder: 'Date of Birth', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :sex %><br>
          <%= f.select :sex, options_for_seasons, class: 'form-control', prompt: 'Select One' %>
        </div>
        <div class="actions">
          <%= submit_tag 'Update', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6 well">
    <h3>Followers</h3>
    <hr>
    <div id="followers">
      <%= render(@followers) || render('shared/no_resource', resources: 'Followers')  %>
    </div>
    <%= render 'shared/paginate', resources: @followers %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/users/followers.js.erb
$('#followers').append("<%= j render(@followers) %>");

<%= render 'shared/paginate', resources: @followers %>

app/views/users/friends.html.erb
<div class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6 well">
    <h3>Friends</h3>
    <hr>
    <div id="friends">
      <%= render(@friends) || render('shared/no_resource', resources: 'Friends') %>
    </div>
    <%= render 'shared/paginate', resources: @friends %>
  </div>
  <div class="col-lg-3">
    <%= render 'shared/links' %>
  </div>
</div>

app/views/users/friends.js.erb
$('#friends').append("<%= j render(@friends) %>");

<%= render 'shared/paginate', resources: @friends %>

app/views/users/show.html.erb
<%= render 'shared/cover', user: @user %>
<br>
<div id="user-<%= @user.id %>" class="row">
  <div class="col-lg-3">
    <%= render 'shared/user_info' %>
  </div>
  <div class="col-lg-6">
    <div id="activities">
      <% if @activities.empty? %>
        <div class="well">
          <%= render('shared/no_resource', resources: 'Activities') %>
        </div>
      <% else %>
        <%= render_activities(@activities, layout: '/shared/activity') %>
      <% end %>
    </div>
    <%= render 'shared/paginate', resources: @activities %>
  </div>
  <div class="col-lg-3">
    <% if is_current_user?(@user) %>
      <div class="well">
        <ul class="nav nav-pills nav-stacked">
          <li><%= link_to 'Edit Profile', edit_user_path(@user) %></li>
          <li><%= link_to 'Change password', edit_user_registration_path %></li>
          <li><%= link_to 'Friends', friends_user_path(@user) %></li>
          <li><%= link_to 'Followers', followers_user_path(@user) %></li>
          <li><%= link_to 'Deactivate', deactivate_user_path(@user) %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.js.erb
$('#activities').append("<%= j render_activities(@activities, layout: '/shared/activity') %>");

<%= render 'shared/paginate', resources: @activities %>